"""Versioned, user-confirmed default costs for paper backtests."""
COMMISSION_RATE = 0.0001
MIN_COMMISSION_CNY = 0.0
SLIPPAGE_BPS = 2
A_SHARE_STOCK_SELL_STAMP_TAX_RATE = 0.0005
A_SHARE_ETF_SELL_STAMP_TAX_RATE = 0.0
HK_STOCK_BUY_STAMP_TAX_RATE = 0.001
HK_STOCK_SELL_STAMP_TAX_RATE = 0.001
COST_MODEL_VERSION = "user-cost-v1"
